REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\mre app\tcp_socket_sample\tcp_socket_sample.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\mre app\tcp_socket_sample\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\mre app\tcp_socket_sample\include" -I "D:\mre app\tcp_socket_sample\include\service" -I "D:\mre app\tcp_socket_sample\include\component" -I "D:\mre app\tcp_socket_sample\ResID" -I "D:\mre app\tcp_socket_sample\src\app\widget" -I "D:\mre app\tcp_socket_sample\src\app\launcher" -I "D:\mre app\tcp_socket_sample\src\app\wallpaper" -I "D:\mre app\tcp_socket_sample\src\app\screen_lock" -I "D:\mre app\tcp_socket_sample\include\service" -I "D:\mre app\tcp_socket_sample\include\component" -I "D:\mre app\tcp_socket_sample\include\service" -I "D:\mre app\tcp_socket_sample\src\framework" -I "D:\mre app\tcp_socket_sample\src\framework\ui_core\base" -I "D:\mre app\tcp_socket_sample\src\framework\ui_core\mvc" -I "D:\mre app\tcp_socket_sample\src\framework\ui_core\pme" -I "D:\mre app\tcp_socket_sample\src\framework\mmi_core" -I "D:\mre app\tcp_socket_sample\src\ui_engine\vrt\interface" -I "D:\mre app\tcp_socket_sample\src\component" -I "D:\mre app\tcp_socket_sample\src\ui_engine\framework\xml" -I "D:\mre app\tcp_socket_sample"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -g -fpic -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\mre app\tcp_socket_sample\arm\tcp_socket_sample.o" -c "d:\mre app\tcp_socket_sample\tcp_socket_sample.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "C:\Program Files\MRE SDK V3.0.00\include" -I "C:\Program Files\MRE SDK V3.0.00\include\service" -I "D:\mre app\tcp_socket_sample\include" -I "D:\mre app\tcp_socket_sample\include\service" -I "D:\mre app\tcp_socket_sample\include\component" -I "D:\mre app\tcp_socket_sample\ResID" -I "D:\mre app\tcp_socket_sample\src\app\widget" -I "D:\mre app\tcp_socket_sample\src\app\launcher" -I "D:\mre app\tcp_socket_sample\src\app\wallpaper" -I "D:\mre app\tcp_socket_sample\src\app\screen_lock" -I "D:\mre app\tcp_socket_sample\include\service" -I "D:\mre app\tcp_socket_sample\include\component" -I "D:\mre app\tcp_socket_sample\include\service" -I "D:\mre app\tcp_socket_sample\src\framework" -I "D:\mre app\tcp_socket_sample\src\framework\ui_core\base" -I "D:\mre app\tcp_socket_sample\src\framework\ui_core\mvc" -I "D:\mre app\tcp_socket_sample\src\framework\ui_core\pme" -I "D:\mre app\tcp_socket_sample\src\framework\mmi_core" -I "D:\mre app\tcp_socket_sample\src\ui_engine\vrt\interface" -I "D:\mre app\tcp_socket_sample\src\component" -I "D:\mre app\tcp_socket_sample\src\ui_engine\framework\xml" -I "D:\mre app\tcp_socket_sample"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\mre app\tcp_socket_sample\tcp_socket_sample.axf"  "D:\mre app\tcp_socket_sample\arm\gccmain.o"  "D:\mre app\tcp_socket_sample\arm\tcp_socket_sample.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\pertcp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persensor.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persmsper.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perbitstream.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percontact.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\permms.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persmsmng.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\peraudio.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percallout.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\percam.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perhttp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persim.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perrecord.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persmssp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perlbs.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perpro.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\pervideo.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perxml.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persec.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perpayment.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perbt.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perpn.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\perudp.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persysfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc_t\persso.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\mre app\tcp_socket_sample\tcp_socket_sample.pkd" -e AXF "D:\mre app\tcp_socket_sample\tcp_socket_sample.vcproj" "D:\mre app\tcp_socket_sample\tcp_socket_sample.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\mre app\tcp_socket_sample\tcp_socket_sample.vcproj" "tcp_socket_sample" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "tcp_socket_sample" "tcp_socket_sample" "tcp_socket_sample" "9246013000350208" "content" " TCP Sensor SMS(person) BitStream Contact MMS SMSMng Audio Call Camera File HTTP SIM card Record SMS(SP) LBS ProMng Video XML Sec SysStorage Payment BT PUSH UDP SysFile sso" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\mre app\tcp_socket_sample\arm D:\mre app\tcp_socket_sample\build.log

